//
// ActivityResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The model that defines the actions that can be taken for a given Activity entry */
public class ActivityResponse: JSONEncodable {
    public enum ActivityResponseType: String { 
        case ConnectionRequestAccept = "connection_request_accept"
        case ConnectionRequestDecline = "connection_request_decline"
        case DateAcceptedChat = "date_accepted_chat"
        case DateSuggestedView = "date_suggested_view"
        case MatchSuggestedView = "match_suggested_view"
        case MatchSuggestedSecondDegreeView = "match_suggested_second_degree_view"
        case MatchAcceptedChat = "match_accepted_chat"
        case MatchAcceptedByMeSuggest = "match_accepted_by_me_suggest"
        case MessageReceivedView = "message_received_view"
    }
    /** The text to show when presenting the response */
    public var text: String?
    /** The different types of responses to activities */
    public var activityResponseType: ActivityResponseType?
    /** The text that describes the action a user took when responding to an activity. Optional. */
    public var responseMessage: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["text"] = self.text
        nillableDictionary["activity_response_type"] = self.activityResponseType?.rawValue
        nillableDictionary["response_message"] = self.responseMessage
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
