//
// ActivityResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The model that defines the actions that can be taken for a given Activity entry */
public class ActivityResponse: JSONEncodable {
    /** The text to show when presenting the response */
    public var text: String?
    public var type: ActivityResponseType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["text"] = self.text
        nillableDictionary["type"] = self.type?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
