//
// BaseUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used when not all user attributes are necessary */
public class BaseUser: JSONEncodable {
    /** User&#39;s first name */
    public var firstName: String?
    /** The root image for the user. Can be resized by appending WxH */
    public var image: String?
    /** User&#39;s last name */
    public var lastName: String?
    /** Unique username for the user; used in URLs */
    public var username: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["first_name"] = self.firstName
        nillableDictionary["image"] = self.image
        nillableDictionary["last_name"] = self.lastName
        nillableDictionary["username"] = self.username
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
