//
// Height.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Height: JSONEncodable {
    public enum Unit: String { 
        case Cm = "cm"
        case In = "in"
    }
    public var amount: Int32?
    public var unit: Unit?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["amount"] = self.amount?.encodeToJSON()
        nillableDictionary["unit"] = self.unit?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
