//
// Match.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents a match with the current user. Could potentially add a second user to this model, but that&#39;s not needed at the moment and is implied to be the currently logged-in user. */
public class Match: JSONEncodable {
    /** The username of the person who suggested the match. This user will only be directly connected to one single in the match. */
    public var matchmakerUsername: String?
    public var user: User?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["matchmaker_username"] = self.matchmakerUsername
        nillableDictionary["user"] = self.user?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
