//
// Message.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Message: JSONEncodable {
    public enum MessageType: String { 
        case Image = "image"
        case Text = "text"
    }
    public var message: String?
    /** The type of message represented by the message property. For image, this is the url where the image is located. The message should be displayed differently for each different type of message. */
    public var messageType: MessageType?
    /** The username of the user who received the message */
    public var recipient: String?
    /** The username of the user who sent the message */
    public var sender: String?
    public var timestamp: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["message"] = self.message
        nillableDictionary["message_type"] = self.messageType?.rawValue
        nillableDictionary["recipient"] = self.recipient
        nillableDictionary["sender"] = self.sender
        nillableDictionary["timestamp"] = self.timestamp?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
