//
// PrivateUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PrivateUser: JSONEncodable {
    public enum Gender: String { 
        case Female = "female"
        case Male = "male"
    }
    public enum MatchWithGender: String { 
        case Female = "female"
        case Male = "male"
    }
    /** User&#39;s first name */
    public var firstName: String?
    /** The root image for the user. Can be resized by appending WxH */
    public var image: String?
    /** User&#39;s last name */
    public var lastName: String?
    /** Unique username for the user; used in URLs */
    public var username: String?
    public var bio: String?
    public var dob: NSDate?
    public var education: Education?
    public var employment: Employment?
    public var gender: Gender?
    /** If True, user will be available to be matched up by matchmakers */
    public var isSingle: Bool?
    public var location: Location?
    public var matchWithGender: MatchWithGender?
    /** The user&#39;s matchmakers */
    public var matchmakers: [BaseUser]?
    /** The user&#39;s singles */
    public var singles: [BaseUser]?
    /** Email address of the user, used as the unique login identifier */
    public var emailAddress: String?
    public var password: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["first_name"] = self.firstName
        nillableDictionary["image"] = self.image
        nillableDictionary["last_name"] = self.lastName
        nillableDictionary["username"] = self.username
        nillableDictionary["bio"] = self.bio
        nillableDictionary["dob"] = self.dob?.encodeToJSON()
        nillableDictionary["education"] = self.education?.encodeToJSON()
        nillableDictionary["employment"] = self.employment?.encodeToJSON()
        nillableDictionary["gender"] = self.gender?.rawValue
        nillableDictionary["is_single"] = self.isSingle
        nillableDictionary["location"] = self.location?.encodeToJSON()
        nillableDictionary["match_with_gender"] = self.matchWithGender?.rawValue
        nillableDictionary["matchmakers"] = self.matchmakers?.encodeToJSON()
        nillableDictionary["singles"] = self.singles?.encodeToJSON()
        nillableDictionary["email_address"] = self.emailAddress
        nillableDictionary["password"] = self.password
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
