//
// Activity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An entry in a user&#39;s activity list */
public class Activity: JSONEncodable {
    /** The endpoints to call in order to respond to the activity */
    public var endpoints: [ActivityEndpoint]?
    /** The URL of the icon to show next the activity entry */
    public var icon: String?
    /** A unique identifier for this activity */
    public var id: Int32?
    /** The text that describes the activity that was performed */
    public var text: String?
    public var timestamp: NSDate?
    public var viewed: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["endpoints"] = self.endpoints?.encodeToJSON()
        nillableDictionary["icon"] = self.icon
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["text"] = self.text
        nillableDictionary["timestamp"] = self.timestamp?.encodeToJSON()
        nillableDictionary["viewed"] = self.viewed
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
