//
// ActivityEndpoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The model that defines the actions that can be taken for a given Activity entry */
public class ActivityEndpoint: JSONEncodable {
    /** The universal identifier of the endpoint for the activity action */
    public var uri: String?
    /** The message to show when calling out the action */
    public var message: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["uri"] = self.uri
        nillableDictionary["message"] = self.message
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
