//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class DefaultAPI: APIBase {
    /**
     * enum for parameter appMode
     */
    public enum AppMode_activityGet: String { 
        case Matchmaker = "matchmaker"
        case Single = "single"
    }

    /**

     - parameter appMode: (query)  (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func activityGet(appMode appMode: AppMode_activityGet? = nil, limit: Int32? = nil, page: Int32? = nil, completion: ((data: [Activity]?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        activityGetWithRequestBuilder(appMode: appMode, limit: limit, page: page).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.activityGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /activity
     - Get the recent activity for the logged-in user, in reverse chronological order
     - examples: [{contentType=application/json, example=[ {
  "response_message" : "aeiou",
  "viewed_at" : "2000-01-23T04:56:07.000+00:00",
  "icon" : "aeiou",
  "origin_user" : {
    "image" : "aeiou",
    "last_name" : "aeiou",
    "first_name" : "aeiou",
    "username" : "aeiou"
  },
  "responses" : [ {
    "response_message" : "aeiou",
    "activity_response_type" : "aeiou",
    "text" : "aeiou"
  } ],
  "attributes" : {
    "id" : "",
    "username" : "aeiou"
  },
  "id" : "",
  "message" : "aeiou",
  "timestamp" : "2000-01-23T04:56:07.000+00:00"
} ]}]
     
     - parameter appMode: (query)  (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)

     - returns: RequestBuilder<[Activity]> 
     */
    public class func activityGetWithRequestBuilder(appMode appMode: AppMode_activityGet? = nil, limit: Int32? = nil, page: Int32? = nil) -> RequestBuilder<[Activity]> {
        let path = "/activity"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "app_mode": appMode?.rawValue,
            "limit": limit?.encodeToJSON(),
            "page": page?.encodeToJSON()
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<[Activity]>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func activityIdGet(id id: Int32, completion: ((data: Activity?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        activityIdGetWithRequestBuilder(id: id).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.activityIdGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.activityIdGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /activity/{id}
     - Get details about a specific activity entry
     - examples: [{contentType=application/json, example={
  "response_message" : "aeiou",
  "viewed_at" : "2000-01-23T04:56:07.000+00:00",
  "icon" : "aeiou",
  "origin_user" : {
    "image" : "aeiou",
    "last_name" : "aeiou",
    "first_name" : "aeiou",
    "username" : "aeiou"
  },
  "responses" : [ {
    "response_message" : "aeiou",
    "activity_response_type" : "aeiou",
    "text" : "aeiou"
  } ],
  "attributes" : {
    "id" : "",
    "username" : "aeiou"
  },
  "id" : "",
  "message" : "aeiou",
  "timestamp" : "2000-01-23T04:56:07.000+00:00"
}}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<Activity> 
     */
    public class func activityIdGetWithRequestBuilder(id id: Int32) -> RequestBuilder<Activity> {
        var path = "/activity/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Activity>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func activityIdPut(id id: Int32, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        activityIdPutWithRequestBuilder(id: id).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.activityIdPut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.activityIdPut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /activity/{id}
     - Set the activity as viewed by the user
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter id: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func activityIdPutWithRequestBuilder(id id: Int32) -> RequestBuilder<Empty> {
        var path = "/activity/{id}"
        path = path.stringByReplacingOccurrencesOfString("{id}", withString: "\(id)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func authDelete(completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        authDeleteWithRequestBuilder().execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.authDelete403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - DELETE /auth
     - Logout the user by invalidating the session-key in the header. Other session-keys for the user may still be valid.
     - examples: [{contentType=application/json, example={ }}]

     - returns: RequestBuilder<Empty> 
     */
    public class func authDeleteWithRequestBuilder() -> RequestBuilder<Empty> {
        let path = "/auth"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter emailAddress: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func authForgotPasswordEmailAddressPut(emailAddress emailAddress: String, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        authForgotPasswordEmailAddressPutWithRequestBuilder(emailAddress: emailAddress).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.authForgotPasswordEmailAddressPut400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.authForgotPasswordEmailAddressPut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /auth/forgot-password/{emailAddress}
     - Initiate the forgot-password process for accounts that use the email login type
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter emailAddress: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func authForgotPasswordEmailAddressPutWithRequestBuilder(emailAddress emailAddress: String) -> RequestBuilder<Empty> {
        var path = "/auth/forgot-password/{emailAddress}"
        path = path.stringByReplacingOccurrencesOfString("{emailAddress}", withString: "\(emailAddress)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**
     * enum for parameter loginType
     */
    public enum LoginType_authLoginTypePut: String { 
        case Email = "email"
        case Facebook = "facebook"
    }

    /**

     - parameter loginType: (path)  
     - parameter loginForm: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func authLoginTypePut(loginType loginType: LoginType_authLoginTypePut, loginForm: LoginForm, completion: ((data: SessionKey?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        authLoginTypePutWithRequestBuilder(loginType: loginType, loginForm: loginForm).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.authLoginTypePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /auth/{loginType}
     - Login the user. The content in the request body is determined by login-type. email: password facebook: auth code
     - examples: [{contentType=application/json, example={
  "start_page" : "aeiou",
  "key" : "aeiou"
}}]
     
     - parameter loginType: (path)  
     - parameter loginForm: (body)  

     - returns: RequestBuilder<SessionKey> 
     */
    public class func authLoginTypePutWithRequestBuilder(loginType loginType: LoginType_authLoginTypePut, loginForm: LoginForm) -> RequestBuilder<SessionKey> {
        var path = "/auth/{loginType}"
        path = path.stringByReplacingOccurrencesOfString("{loginType}", withString: "\(loginType.rawValue)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = loginForm.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<SessionKey>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func connectionsUsernameDelete(username username: String, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        connectionsUsernameDeleteWithRequestBuilder(username: username).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.connectionsUsernameDelete403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - DELETE /connections/{username}
     - Remove the connection between the \"username\" user and the logged-in user
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func connectionsUsernameDeleteWithRequestBuilder(username username: String) -> RequestBuilder<Empty> {
        var path = "/connections/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func connectionsUsernamePut(username username: String, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        connectionsUsernamePutWithRequestBuilder(username: username).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.connectionsUsernamePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.connectionsUsernamePut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /connections/{username}
     - Accept a connection request from the \"username\" user to the logged-in user
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func connectionsUsernamePutWithRequestBuilder(username username: String) -> RequestBuilder<Empty> {
        var path = "/connections/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter contentType: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func contentContentTypeGet(contentType contentType: String, completion: ((data: Content?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        contentContentTypeGetWithRequestBuilder(contentType: contentType).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(404, data, _): err = ErrorResponse.contentContentTypeGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /content/{contentType}
     - Get static content. Current supported content-type: invite.message, tos, privacy-policy, faq.
     - examples: [{contentType=application/json, example={
  "content" : [ "aeiou" ]
}}]
     
     - parameter contentType: (path)  

     - returns: RequestBuilder<Content> 
     */
    public class func contentContentTypeGetWithRequestBuilder(contentType contentType: String) -> RequestBuilder<Content> {
        var path = "/content/{contentType}"
        path = path.stringByReplacingOccurrencesOfString("{contentType}", withString: "\(contentType)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Content>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter contentType: (path)  
     - parameter language: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func contentContentTypeLanguageGet(contentType contentType: String, language: String, completion: ((data: Content?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        contentContentTypeLanguageGetWithRequestBuilder(contentType: contentType, language: language).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(404, data, _): err = ErrorResponse.contentContentTypeLanguageGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /content/{contentType}/{language}
     - Get static content. Current supported content-type: invite.message, tos, privacy-policy, faq.
     - examples: [{contentType=application/json, example={
  "content" : [ "aeiou" ]
}}]
     
     - parameter contentType: (path)  
     - parameter language: (path)  

     - returns: RequestBuilder<Content> 
     */
    public class func contentContentTypeLanguageGetWithRequestBuilder(contentType contentType: String, language: String) -> RequestBuilder<Content> {
        var path = "/content/{contentType}/{language}"
        path = path.stringByReplacingOccurrencesOfString("{contentType}", withString: "\(contentType)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{language}", withString: "\(language)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Content>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**
     * enum for parameter matchType
     */
    public enum MatchType_matchesGet: String { 
        case Accepted = "accepted"
        case Pending = "pending"
    }

    /**

     - parameter matchType: (query)  (optional, default to accepted)
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func matchesGet(matchType matchType: MatchType_matchesGet? = nil, limit: Int32? = nil, page: Int32? = nil, completion: ((data: [User]?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        matchesGetWithRequestBuilder(matchType: matchType, limit: limit, page: page).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.matchesGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /matches
     - Get the list of active matches for the logged-in user. Use the match_type parameter to determine which type of matches are returned: matches that were already accepted vs pending matches that must be accepted by one party. If page > 0 and the result list is empty, there are no more connected users to show.
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - examples: [{contentType=application/json, example=[ "" ]}]
     
     - parameter matchType: (query)  (optional, default to accepted)
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)

     - returns: RequestBuilder<[User]> 
     */
    public class func matchesGetWithRequestBuilder(matchType matchType: MatchType_matchesGet? = nil, limit: Int32? = nil, page: Int32? = nil) -> RequestBuilder<[User]> {
        let path = "/matches"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "match_type": matchType?.rawValue,
            "limit": limit?.encodeToJSON(),
            "page": page?.encodeToJSON()
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<[User]>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter date: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func matchesUsernameDatesDatePut(username username: String, date: NSDate, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        matchesUsernameDatesDatePutWithRequestBuilder(username: username, date: date).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.matchesUsernameDatesDatePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.matchesUsernameDatesDatePut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /matches/{username}/dates/{date}
     - Accept the given date
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  
     - parameter date: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func matchesUsernameDatesDatePutWithRequestBuilder(username username: String, date: NSDate) -> RequestBuilder<Empty> {
        var path = "/matches/{username}/dates/{date}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{date}", withString: "\(date)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func matchesUsernameDatesGet(username username: String, completion: ((data: Dates?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        matchesUsernameDatesGetWithRequestBuilder(username: username).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.matchesUsernameDatesGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.matchesUsernameDatesGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /matches/{username}/dates
     - Lists the dates (date and time) that the :username user has suggested to meet with the logged-in user.
     - examples: [{contentType=application/json, example={
  "dates" : [ "2000-01-23T04:56:07.000+00:00" ]
}}]
     
     - parameter username: (path)  

     - returns: RequestBuilder<Dates> 
     */
    public class func matchesUsernameDatesGetWithRequestBuilder(username username: String) -> RequestBuilder<Dates> {
        var path = "/matches/{username}/dates"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Dates>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter dates: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func matchesUsernameDatesPut(username username: String, dates: Dates, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        matchesUsernameDatesPutWithRequestBuilder(username: username, dates: dates).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.matchesUsernameDatesPut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.matchesUsernameDatesPut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /matches/{username}/dates
     - Suggest times for dates with the matched user
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  
     - parameter dates: (body)  

     - returns: RequestBuilder<Empty> 
     */
    public class func matchesUsernameDatesPutWithRequestBuilder(username username: String, dates: Dates) -> RequestBuilder<Empty> {
        var path = "/matches/{username}/dates"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = dates.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func matchesUsernameDelete(username username: String, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        matchesUsernameDeleteWithRequestBuilder(username: username).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.matchesUsernameDelete403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - DELETE /matches/{username}
     - Logged-in user declines a suggested match with the given username. Will notify the other single and all associated matchmakers.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func matchesUsernameDeleteWithRequestBuilder(username username: String) -> RequestBuilder<Empty> {
        var path = "/matches/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func matchesUsernamePut(username username: String, completion: ((data: Status?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        matchesUsernamePutWithRequestBuilder(username: username).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(202, data, _): err = ErrorResponse.matchesUsernamePut202(try Decoders.decode(clazz: Status.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.matchesUsernamePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.matchesUsernamePut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /matches/{username}
     - Logged-in user accepts a suggested match with the given username. Will notify the other single and all associated matchmakers.
     - examples: [{contentType=application/json, example={
  "status" : "aeiou"
}}]
     
     - parameter username: (path)  

     - returns: RequestBuilder<Status> 
     */
    public class func matchesUsernamePutWithRequestBuilder(username username: String) -> RequestBuilder<Status> {
        var path = "/matches/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Status>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func matchmakersGet(limit limit: Int32? = nil, page: Int32? = nil, completion: ((data: [User]?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        matchmakersGetWithRequestBuilder(limit: limit, page: page).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.matchmakersGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /matchmakers
     - Get the list of matchmakers for the logged-in user. If page > 0 and the result list is empty, there are no more connected users to show.
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - examples: [{contentType=application/json, example=[ "" ]}]
     
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)

     - returns: RequestBuilder<[User]> 
     */
    public class func matchmakersGetWithRequestBuilder(limit limit: Int32? = nil, page: Int32? = nil) -> RequestBuilder<[User]> {
        let path = "/matchmakers"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "limit": limit?.encodeToJSON(),
            "page": page?.encodeToJSON()
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<[User]>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func meGet(completion: ((data: PrivateUser?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        meGetWithRequestBuilder().execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.meGet400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.meGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /me
     - Get the logged-in user's information.
     - examples: [{contentType=application/json, example=""}]

     - returns: RequestBuilder<PrivateUser> 
     */
    public class func meGetWithRequestBuilder() -> RequestBuilder<PrivateUser> {
        let path = "/me"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<PrivateUser>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter image: (form)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func meImagePost(image image: FileUpload, completion: ((data: Image?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        meImagePostWithRequestBuilder(image: image).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.meImagePost400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.meImagePost403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(413, data, _): err = ErrorResponse.meImagePost413(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - POST /me/image
     - Upload an image for the logged-in user. Will automatically set the user's image URL to the URL where the image is saved. Only JPG and PNG are supported.
     - examples: [{contentType=application/json, example={
  "url" : "aeiou"
}}]
     
     - parameter image: (form)  

     - returns: RequestBuilder<Image> 
     */
    public class func meImagePostWithRequestBuilder(image image: FileUpload) -> RequestBuilder<Image> {
        let path = "/me/image"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "image": image
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Image>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func meIsSingleDelete(completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        meIsSingleDeleteWithRequestBuilder().execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.meIsSingleDelete400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.meIsSingleDelete403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - DELETE /me/is-single
     - Toggle the \"single\" flag to false. All users are considered available to be matchmakers.
     - examples: [{contentType=application/json, example={ }}]

     - returns: RequestBuilder<Empty> 
     */
    public class func meIsSingleDeleteWithRequestBuilder() -> RequestBuilder<Empty> {
        let path = "/me/is-single"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func meIsSinglePut(completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        meIsSinglePutWithRequestBuilder().execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.meIsSinglePut400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.meIsSinglePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /me/is-single
     - Toggle the \"single\" flag to true. All users are considered available to be matchmakers.
     - examples: [{contentType=application/json, example={ }}]

     - returns: RequestBuilder<Empty> 
     */
    public class func meIsSinglePutWithRequestBuilder() -> RequestBuilder<Empty> {
        let path = "/me/is-single"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**
     * enum for parameter gender
     */
    public enum Gender_meMatchWithGenderPut: String { 
        case Any = "any"
        case Female = "female"
        case Male = "male"
    }

    /**

     - parameter gender: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func meMatchWithGenderPut(gender gender: Gender_meMatchWithGenderPut, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        meMatchWithGenderPutWithRequestBuilder(gender: gender).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.meMatchWithGenderPut400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.meMatchWithGenderPut403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /me/match-with/{gender}
     - Set the gender preference that the single would like to be paired with. Set to empty string for any gender.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter gender: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func meMatchWithGenderPutWithRequestBuilder(gender gender: Gender_meMatchWithGenderPut) -> RequestBuilder<Empty> {
        var path = "/me/match-with/{gender}"
        path = path.stringByReplacingOccurrencesOfString("{gender}", withString: "\(gender.rawValue)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter passwordForm: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func mePasswordPut(passwordForm passwordForm: PasswordForm, completion: ((data: SessionKey?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        mePasswordPutWithRequestBuilder(passwordForm: passwordForm).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.mePasswordPut400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.mePasswordPut403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /me/password
     - Set password for the logged-in user.
     - examples: [{contentType=application/json, example={
  "start_page" : "aeiou",
  "key" : "aeiou"
}}]
     
     - parameter passwordForm: (body)  

     - returns: RequestBuilder<SessionKey> 
     */
    public class func mePasswordPutWithRequestBuilder(passwordForm passwordForm: PasswordForm) -> RequestBuilder<SessionKey> {
        let path = "/me/password"
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = passwordForm.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<SessionKey>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter user: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func mePut(user user: UserForm, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        mePutWithRequestBuilder(user: user).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.mePut400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.mePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /me
     - Update the logged-in user's record.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter user: (body)  

     - returns: RequestBuilder<Empty> 
     */
    public class func mePutWithRequestBuilder(user user: UserForm) -> RequestBuilder<Empty> {
        let path = "/me"
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = user.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func messagesUsernameGet(username username: String, limit: Int32? = nil, page: Int32? = nil, completion: ((data: [Message]?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        messagesUsernameGetWithRequestBuilder(username: username, limit: limit, page: page).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.messagesUsernameGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.messagesUsernameGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /messages/{username}
     - Get the messages sent between the logged in user and the \"username\" user, ordered reverse chronologically
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - examples: [{contentType=application/json, example=[ {
  "sender" : "aeiou",
  "recipient" : "aeiou",
  "message_type" : "aeiou",
  "message" : "aeiou",
  "timestamp" : "2000-01-23T04:56:07.000+00:00"
} ]}]
     
     - parameter username: (path)  
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)

     - returns: RequestBuilder<[Message]> 
     */
    public class func messagesUsernameGetWithRequestBuilder(username username: String, limit: Int32? = nil, page: Int32? = nil) -> RequestBuilder<[Message]> {
        var path = "/messages/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "limit": limit?.encodeToJSON(),
            "page": page?.encodeToJSON()
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<[Message]>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter image: (form)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func messagesUsernameImagePost(username username: String, image: FileUpload, completion: ((data: Image?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        messagesUsernameImagePostWithRequestBuilder(username: username, image: image).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.messagesUsernameImagePost400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.messagesUsernameImagePost403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(413, data, _): err = ErrorResponse.messagesUsernameImagePost413(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - POST /messages/{username}/image
     - Upload an image to be sent from logged-in user to the username user. Only JPG and PNG are supported.
     - examples: [{contentType=application/json, example={
  "url" : "aeiou"
}}]
     
     - parameter username: (path)  
     - parameter image: (form)  

     - returns: RequestBuilder<Image> 
     */
    public class func messagesUsernameImagePostWithRequestBuilder(username username: String, image: FileUpload) -> RequestBuilder<Image> {
        var path = "/messages/{username}/image"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "image": image
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Image>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter message: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func messagesUsernamePut(username username: String, message: MessageForm, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        messagesUsernamePutWithRequestBuilder(username: username, message: message).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.messagesUsernamePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.messagesUsernamePut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /messages/{username}
     - Send a message from the logged in user to the \"username\" user
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  
     - parameter message: (body)  

     - returns: RequestBuilder<Empty> 
     */
    public class func messagesUsernamePutWithRequestBuilder(username username: String, message: MessageForm) -> RequestBuilder<Empty> {
        var path = "/messages/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = message.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func singlesGet(limit limit: Int32? = nil, page: Int32? = nil, completion: ((data: [User]?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        singlesGetWithRequestBuilder(limit: limit, page: page).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.singlesGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /singles
     - Get the list of singles for the logged-in user. If page > 0 and the result list is empty, there are no more connected users to show.
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - examples: [{contentType=application/json, example=[ "" ]}]
     
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)

     - returns: RequestBuilder<[User]> 
     */
    public class func singlesGetWithRequestBuilder(limit limit: Int32? = nil, page: Int32? = nil) -> RequestBuilder<[User]> {
        let path = "/singles"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "limit": limit?.encodeToJSON(),
            "page": page?.encodeToJSON()
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<[User]>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter matchUsername: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func singlesUsernamePatch(username username: String, matchUsername: UserName, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        singlesUsernamePatchWithRequestBuilder(username: username, matchUsername: matchUsername).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.singlesUsernamePatch400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.singlesUsernamePatch403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.singlesUsernamePatch404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PATCH /singles/{username}
     - For matchmaker mode only. Mark the logged-in matchmaker's connected single as having been viewed next to the match_username user. Fails if either party is not a single.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  
     - parameter matchUsername: (body)  

     - returns: RequestBuilder<Empty> 
     */
    public class func singlesUsernamePatchWithRequestBuilder(username username: String, matchUsername: UserName) -> RequestBuilder<Empty> {
        var path = "/singles/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = matchUsername.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PATCH", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter matchUsername: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func singlesUsernamePut(username username: String, matchUsername: UserName, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        singlesUsernamePutWithRequestBuilder(username: username, matchUsername: matchUsername).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.singlesUsernamePut400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.singlesUsernamePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.singlesUsernamePut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /singles/{username}
     - For matchmaker mode only. Set-up the logged-in matchmaker's connected single with the match_username user. Fails if either party is not a single. All matchmakers connected to the single will be notified of the match. Both singles in the match will also be notified of the match.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  
     - parameter matchUsername: (body)  

     - returns: RequestBuilder<Empty> 
     */
    public class func singlesUsernamePutWithRequestBuilder(username username: String, matchUsername: UserName) -> RequestBuilder<Empty> {
        var path = "/singles/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = matchUsername.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_subscriptionsTypeDelete: String { 
        case IosPush = "ios_push"
    }

    /**

     - parameter type: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func subscriptionsTypeDelete(type type: ModelType_subscriptionsTypeDelete, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        subscriptionsTypeDeleteWithRequestBuilder(type: type).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.subscriptionsTypeDelete400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.subscriptionsTypeDelete403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.subscriptionsTypeDelete404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - DELETE /subscriptions/{type}
     - Delete the subscription to the given subscription type.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter type: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func subscriptionsTypeDeleteWithRequestBuilder(type type: ModelType_subscriptionsTypeDelete) -> RequestBuilder<Empty> {
        var path = "/subscriptions/{type}"
        path = path.stringByReplacingOccurrencesOfString("{type}", withString: "\(type.rawValue)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_subscriptionsTypeGet: String { 
        case IosPush = "ios_push"
    }

    /**

     - parameter type: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func subscriptionsTypeGet(type type: ModelType_subscriptionsTypeGet, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        subscriptionsTypeGetWithRequestBuilder(type: type).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.subscriptionsTypeGet400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.subscriptionsTypeGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.subscriptionsTypeGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /subscriptions/{type}
     - Get the status of the subscription to the given subscription type.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter type: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func subscriptionsTypeGetWithRequestBuilder(type type: ModelType_subscriptionsTypeGet) -> RequestBuilder<Empty> {
        var path = "/subscriptions/{type}"
        path = path.stringByReplacingOccurrencesOfString("{type}", withString: "\(type.rawValue)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**
     * enum for parameter type
     */
    public enum ModelType_subscriptionsTypePut: String { 
        case IosPush = "ios_push"
    }

    /**

     - parameter type: (path)  
     - parameter metadata: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func subscriptionsTypePut(type type: ModelType_subscriptionsTypePut, metadata: SubscriptionMetadata? = nil, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        subscriptionsTypePutWithRequestBuilder(type: type, metadata: metadata).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.subscriptionsTypePut400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.subscriptionsTypePut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.subscriptionsTypePut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /subscriptions/{type}
     - Add the subscription to the given subscription type.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter type: (path)  
     - parameter metadata: (body)  (optional)

     - returns: RequestBuilder<Empty> 
     */
    public class func subscriptionsTypePutWithRequestBuilder(type type: ModelType_subscriptionsTypePut, metadata: SubscriptionMetadata? = nil) -> RequestBuilder<Empty> {
        var path = "/subscriptions/{type}"
        path = path.stringByReplacingOccurrencesOfString("{type}", withString: "\(type.rawValue)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = metadata?.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter version: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func supportedVersionsVersionGet(version version: String, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        supportedVersionsVersionGetWithRequestBuilder(version: version).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(404, data, _): err = ErrorResponse.supportedVersionsVersionGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /supported-versions/{version}
     - Check to see if the given version is supported by the app.
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter version: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func supportedVersionsVersionGetWithRequestBuilder(version version: String) -> RequestBuilder<Empty> {
        var path = "/supported-versions/{version}"
        path = path.stringByReplacingOccurrencesOfString("{version}", withString: "\(version)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter matchmaker: (query) Find only singles connected to this matchmaker (username). (optional)
     - parameter query: (query) Text to search for. Will look at the user&#39;s name and username. (optional)
     - parameter singlesOnly: (query) Use this to filter only singles or matchmakers. (optional)
     - parameter excludeMyConnections: (query) Set to true if the logged-in user&#39;s connections should not be included in the results. (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func usersGet(matchmaker matchmaker: String? = nil, query: String? = nil, singlesOnly: Bool? = nil, excludeMyConnections: Bool? = nil, limit: Int32? = nil, page: Int32? = nil, completion: ((data: [User]?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        usersGetWithRequestBuilder(matchmaker: matchmaker, query: query, singlesOnly: singlesOnly, excludeMyConnections: excludeMyConnections, limit: limit, page: page).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.usersGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /users
     - Search for users
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - examples: [{contentType=application/json, example=[ "" ]}]
     
     - parameter matchmaker: (query) Find only singles connected to this matchmaker (username). (optional)
     - parameter query: (query) Text to search for. Will look at the user&#39;s name and username. (optional)
     - parameter singlesOnly: (query) Use this to filter only singles or matchmakers. (optional)
     - parameter excludeMyConnections: (query) Set to true if the logged-in user&#39;s connections should not be included in the results. (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)

     - returns: RequestBuilder<[User]> 
     */
    public class func usersGetWithRequestBuilder(matchmaker matchmaker: String? = nil, query: String? = nil, singlesOnly: Bool? = nil, excludeMyConnections: Bool? = nil, limit: Int32? = nil, page: Int32? = nil) -> RequestBuilder<[User]> {
        let path = "/users"
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "matchmaker": matchmaker,
            "query": query,
            "singles_only": singlesOnly,
            "exclude_my_connections": excludeMyConnections,
            "limit": limit?.encodeToJSON(),
            "page": page?.encodeToJSON()
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<[User]>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter userForm: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func usersPut(userForm userForm: UserForm? = nil, completion: ((data: SessionKey?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        usersPutWithRequestBuilder(userForm: userForm).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(400, data, _): err = ErrorResponse.usersPut400(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(403, data, _): err = ErrorResponse.usersPut403(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /users
     - Create a user. Either PrivateUser or fb-auth-code is required (see UserForm defintion for details). For user profile updates, see PUT /me.
     - examples: [{contentType=application/json, example={
  "start_page" : "aeiou",
  "key" : "aeiou"
}}]
     
     - parameter userForm: (body)  (optional)

     - returns: RequestBuilder<SessionKey> 
     */
    public class func usersPutWithRequestBuilder(userForm userForm: UserForm? = nil) -> RequestBuilder<SessionKey> {
        let path = "/users"
        let URLString = ThreeDegreesClientAPI.basePath + path
        let parameters = userForm?.encodeToJSON() as? [String:AnyObject]

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<SessionKey>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func usersUsernameConnectionsPut(username username: String, completion: ((data: Empty?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        usersUsernameConnectionsPutWithRequestBuilder(username: username).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.usersUsernameConnectionsPut403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.usersUsernameConnectionsPut404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - PUT /users/{username}/connections
     - Add a connection request from the logged-in user to the \"username\" user
     - examples: [{contentType=application/json, example={ }}]
     
     - parameter username: (path)  

     - returns: RequestBuilder<Empty> 
     */
    public class func usersUsernameConnectionsPutWithRequestBuilder(username username: String) -> RequestBuilder<Empty> {
        var path = "/users/{username}/connections"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<Empty>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**

     - parameter username: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func usersUsernameGet(username username: String, completion: ((data: User?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        usersUsernameGetWithRequestBuilder(username: username).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(404, data, _): err = ErrorResponse.usersUsernameGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /users/{username}
     - Get user details
     - examples: [{contentType=application/json, example=""}]
     
     - parameter username: (path)  

     - returns: RequestBuilder<User> 
     */
    public class func usersUsernameGetWithRequestBuilder(username username: String) -> RequestBuilder<User> {
        var path = "/users/{username}"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<User>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

    /**
     * enum for parameter gender
     */
    public enum Gender_usersUsernamePotentialMatchesGet: String { 
        case Female = "female"
        case Male = "male"
    }

    /**

     - parameter username: (path)  
     - parameter ageFrom: (query) Filter the results to only results within this age range. (optional)
     - parameter ageTo: (query) Filter the results to only results within this age range. (optional)
     - parameter gender: (query)  (optional)
     - parameter matchmaker: (query) Find only singles connected to this matchmaker (username). (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func usersUsernamePotentialMatchesGet(username username: String, ageFrom: Int32? = nil, ageTo: Int32? = nil, gender: Gender_usersUsernamePotentialMatchesGet? = nil, matchmaker: String? = nil, limit: Int32? = nil, page: Int32? = nil, completion: ((data: [User]?, error: ErrorType?, headers: Dictionary<NSObject, AnyObject>) -> Void)) {
        usersUsernamePotentialMatchesGetWithRequestBuilder(username: username, ageFrom: ageFrom, ageTo: ageTo, gender: gender, matchmaker: matchmaker, limit: limit, page: page).execute { (response, rawError, headers) -> Void in
            var err: ErrorType? = nil
            do {
                if let e = rawError {
                    switch e {
                        case let .RawError(403, data, _): err = ErrorResponse.usersUsernamePotentialMatchesGet403(try Decoders.decode(clazz: Error.self, source: data!))
                        case let .RawError(404, data, _): err = ErrorResponse.usersUsernamePotentialMatchesGet404(try Decoders.decode(clazz: Error.self, source: data!))
                        default: err = e
                    }
                }
            } catch {
                err = error
            }
            completion(data: response?.body, error: err, headers: headers);
        }
    }


    /**
     - GET /users/{username}/potential-matches
     - List of other singles that the given user could be matched with. The given user must be directly connected to the logged-in user; the potential matches will be the singles of the matchmakers in the logged-in user's network.
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - responseHeaders: [count(Int32), limit(Int32), page(Int32)]
     - examples: [{contentType=application/json, example=[ "" ]}]
     
     - parameter username: (path)  
     - parameter ageFrom: (query) Filter the results to only results within this age range. (optional)
     - parameter ageTo: (query) Filter the results to only results within this age range. (optional)
     - parameter gender: (query)  (optional)
     - parameter matchmaker: (query) Find only singles connected to this matchmaker (username). (optional)
     - parameter limit: (query)  (optional, default to 100)
     - parameter page: (query)  (optional, default to 0)

     - returns: RequestBuilder<[User]> 
     */
    public class func usersUsernamePotentialMatchesGetWithRequestBuilder(username username: String, ageFrom: Int32? = nil, ageTo: Int32? = nil, gender: Gender_usersUsernamePotentialMatchesGet? = nil, matchmaker: String? = nil, limit: Int32? = nil, page: Int32? = nil) -> RequestBuilder<[User]> {
        var path = "/users/{username}/potential-matches"
        path = path.stringByReplacingOccurrencesOfString("{username}", withString: "\(username)", options: .LiteralSearch, range: nil)
        let URLString = ThreeDegreesClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "age_from": ageFrom?.encodeToJSON(),
            "age_to": ageTo?.encodeToJSON(),
            "gender": gender?.rawValue,
            "matchmaker": matchmaker,
            "limit": limit?.encodeToJSON(),
            "page": page?.encodeToJSON()
        ]

        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilderClass: RequestBuilder<[User]>.Type = ThreeDegreesClientAPI.requestBuilderFactory.getBuilder()
        let requestBuilder = requestBuilderClass.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
        requestBuilder.addHeaders(["Accept": "application/json"])
        return requestBuilder
    }

}
